/**
 * The two bearer credentials `approval serve` reads from its launch
 * environment, and the scope each one buys (APRV-421).
 *
 * ## Two credentials, because there are two parties
 *
 * SPEC.md §11 names the agent the untrusted policy and the human the trusted
 * overseer, and a hosted deployment adds a third fact: the log and the policy
 * belong to the TENANT, while the harness that is judged by them runs
 * somewhere else entirely (design/hosted-daemon-identity.md, §1). So this
 * server has two doors and never one.
 *
 * - The **agent credential** ({@link AGENT_TOKEN_ENV}) reaches the
 *   agent-facing verb surface and the harness hook. It is the credential a
 *   sandbox holds, and the sandbox is the party under oversight.
 * - The **tenant credential** ({@link TENANT_TOKEN_ENV}) reaches the log, the
 *   export and the status report. It is the credential the tenant's own tools
 *   hold.
 *
 * **The agent credential must never read the log it is judged by.** That is
 * the sentence the split exists for. An agent that can stream the verified log
 * can read every decision made about it, every other action in the tenant's
 * store, and the shape of the oversight it is under; an agent that can export
 * the store can carry all of it away. Neither is a thing the gate would ever
 * grant, so neither is reachable with the credential the gate hands the
 * harness. The refusal is a scope refusal and not a not-found, because a
 * caller that guessed a path deserves to learn that the door exists and is not
 * theirs, rather than to probe for one that answers differently.
 *
 * ## Why the environment
 *
 * SPEC.md §11.1 invariant 7: configuration is never loaded implicitly from the
 * working tree. A credential in a file this process discovered would be a
 * credential anything able to write that file could rotate. The host that
 * launches one process per tenant is the party that sets these, exactly as it
 * sets the bot token, the sampling secret and the vault passphrase
 * (design/hosted-daemon-identity.md §1.2).
 *
 * ## What comparison costs
 *
 * Both values are compared as SHA-256 digests under `timingSafeEqual`, so the
 * comparison is constant-time AND length-independent: `timingSafeEqual` throws
 * on a length mismatch, which would itself be an oracle for the length of the
 * real credential. Nothing here logs, prints, or returns either value, and the
 * server never puts one in a record, a message or a header.
 */

import { createHash, timingSafeEqual } from "node:crypto";

/** The environment variable naming the credential a sandboxed harness holds. */
export const AGENT_TOKEN_ENV = "APPROVAL_SERVE_AGENT_TOKEN";

/** The environment variable naming the credential the tenant's own tools hold. */
export const TENANT_TOKEN_ENV = "APPROVAL_SERVE_TENANT_TOKEN";

/**
 * The shortest credential this server will start with.
 *
 * Not a password policy: a floor under the one mistake that makes the split
 * meaningless, which is a memorable value somebody typed. The credential is
 * generated by the host, never by a person, so the floor costs nothing.
 */
export const MIN_TOKEN_LENGTH = 24;

/** Which of the two parties a request is acting as. */
export type ServeScope = "agent" | "tenant";

/**
 * The frozen refusal vocabulary of the credential layer (SPEC.md §11.1
 * invariant 6). Distinct codes, because the repairs are distinct: one is a
 * missing or wrong credential, and the other two are the right credential at
 * the wrong door, in each direction.
 */
export const SERVE_CREDENTIAL_REFUSAL_CODES = [
  "serve-unauthorized",
  "serve-agent-forbidden",
  "serve-tenant-forbidden",
] as const;

export type ServeCredentialRefusalCode = (typeof SERVE_CREDENTIAL_REFUSAL_CODES)[number];

/** Hold the digests, never the values. */
export interface ServeCredentials {
  /** Which scope this bearer value belongs to, or `null` for neither. */
  identify(bearer: string): ServeScope | null;
}

export type CredentialResolution =
  | { ok: true; credentials: ServeCredentials }
  | { ok: false; message: string };

function digest(value: string): Buffer {
  return createHash("sha256").update(value, "utf8").digest();
}

function sameDigest(left: Buffer, right: Buffer): boolean {
  // Equal by construction (two SHA-256 digests), so `timingSafeEqual` can never
  // throw here and the comparison leaks nothing about the length of either
  // input.
  return timingSafeEqual(left, right);
}

/**
 * Resolve both credentials, or say why the server may not start.
 *
 * Every failure is a STARTUP failure. A server that began listening and then
 * discovered it had no tenant credential would be a server something had
 * already spoken to, which is the rule `cli/mcp.ts` states for identity and
 * this file inherits for authority.
 */
export function resolveServeCredentials(
  env: NodeJS.ProcessEnv = process.env,
): CredentialResolution {
  const agent = env[AGENT_TOKEN_ENV] ?? "";
  const tenant = env[TENANT_TOKEN_ENV] ?? "";

  for (const [name, value] of [
    [AGENT_TOKEN_ENV, agent],
    [TENANT_TOKEN_ENV, tenant],
  ] as const) {
    if (value.length === 0) {
      return {
        ok: false,
        message: `no ${name} in the environment: this server has two doors and starts only when the host has named both. The agent credential reaches the verbs and the hook; the tenant credential reaches the log, the export and status`,
      };
    }
    if (value.length < MIN_TOKEN_LENGTH) {
      return {
        ok: false,
        message: `${name} is shorter than ${String(MIN_TOKEN_LENGTH)} characters. Generate it (\`openssl rand -hex 32\`) rather than choosing it: this value is the whole of what separates the two parties`,
      };
    }
  }

  if (sameDigest(digest(agent), digest(tenant))) {
    return {
      ok: false,
      message: `${AGENT_TOKEN_ENV} and ${TENANT_TOKEN_ENV} are the same value, which is the same as having neither: the agent credential would reach the log it is judged by`,
    };
  }

  const agentDigest = digest(agent);
  const tenantDigest = digest(tenant);
  return {
    ok: true,
    credentials: {
      identify(bearer: string): ServeScope | null {
        const offered = digest(bearer);
        // Both compared, always, in the same order: returning as soon as the
        // agent digest matched would make an agent credential measurably
        // faster to present than a tenant one.
        const isAgent = sameDigest(offered, agentDigest);
        const isTenant = sameDigest(offered, tenantDigest);
        if (isAgent) return "agent";
        if (isTenant) return "tenant";
        return null;
      },
    },
  };
}

/** The bearer value of an `Authorization` header, or null. */
export function bearerOf(header: string | string[] | undefined): string | null {
  const raw = Array.isArray(header) ? header[0] : header;
  if (raw === undefined) return null;
  const match = /^Bearer[ \t]+(?<token>\S+)$/iu.exec(raw.trim());
  return match?.groups?.["token"] ?? null;
}
